
[functions.prepare-payment-link]
enabled = true
verify_jwt = false
import_map = "./functions/prepare-payment-link/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/prepare-payment-link/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/prepare-payment-link/*.html" ]

[functions.send-registration-email]
enabled = true
verify_jwt = false
import_map = "./functions/send-registration-email/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/send-registration-email/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/send-registration-email/*.html" ]

[functions.create-admin-user]
enabled = true
verify_jwt = true
import_map = "./functions/create-admin-user/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/create-admin-user/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/create-admin-user/*.html" ]

[functions.list-admin-users]
enabled = true
verify_jwt = true
import_map = "./functions/list-admin-users/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/list-admin-users/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/list-admin-users/*.html" ]

[functions.delete-admin-user]
enabled = true
verify_jwt = true
import_map = "./functions/delete-admin-user/deno.json"
entrypoint = "./functions/delete-admin-user/index.ts"
